#ifndef __ASM_MACH_IRQS_H
#define __ASM_MACH_IRQS_H

/* Interrupt numbers definitions */
#define IRQ_LOCALTIMER				29
#define IRQ_LOCALWDT				30

#define IRQ_GIC_START				32
#define GALOIS_APB_IRQ_START			(32 + IRQ_GIC_START)
#define GALOIS_SM_IRQ_START			(64 + IRQ_GIC_START)

#define IRQ_DHUBINTRAVIO0			(0 + IRQ_GIC_START)
#define IRQ_DHUBINTRAVIO1			(1 + IRQ_GIC_START)
#define IRQ_DHUBINTRVPRO			(2 + IRQ_GIC_START)
#define IRQ_ICTLINST0CPUIRQ			(3 + IRQ_GIC_START)
#define IRQ_CTI_NCTIIRQ_0			(4 + IRQ_GIC_START)
#define IRQ_INTRGFX3DM0				(5 + IRQ_GIC_START)
#define IRQ_INTRGFXM0				(6 + IRQ_GIC_START)
#define IRQ_SATAINTR				(7 + IRQ_GIC_START)
#define IRQ_ETHIRQ				(8 + IRQ_GIC_START)
#define IRQ_DRMINTR				(9 + IRQ_GIC_START)
#define IRQ_DRMFIGOINTR				(10 + IRQ_GIC_START)
#define IRQ_USB0INTERRUPT			(11 + IRQ_GIC_START)
#define IRQ_USB1INTERRUPT			(12 + IRQ_GIC_START)
#define IRQ_SM2SOCINT				(13 + IRQ_GIC_START)
#define IRQ_PTPIRQ				(14 + IRQ_GIC_START)
#define IRQ_SM2SOCHWINT0			(15 + IRQ_GIC_START)
#define IRQ_SM2SOCHWINT1			(16 + IRQ_GIC_START)
#define IRQ_SDIO_INTERRUPT			(17 + IRQ_GIC_START)
#define IRQ_INTRPB				(18 + IRQ_GIC_START)
#define IRQ_ZSPINT				(19 + IRQ_GIC_START)
#define IRQ_SDIO1_INTERRUPT			(20 + IRQ_GIC_START)
#define IRQ_SPDIF_RX_CHOVR_INTR			(21 + IRQ_GIC_START)
#define IRQ_SPDIF_RX_INTR			(22 + IRQ_GIC_START)
#define IRQ_GC360INTR				(23 + IRQ_GIC_START)
#define IRQ_ETH1IRQ				(24 + IRQ_GIC_START)
#define IRQ_DHUBINTRAVIO2			(25 + IRQ_GIC_START)
#define IRQ_INTRHWBLK				(26 + IRQ_GIC_START)
#define IRQ_INTRFIGO				(27 + IRQ_GIC_START)
#define IRQ_MMC_INTERRUPT			(28 + IRQ_GIC_START)
#define IRQ_CTI_NCTIIRQ_1			(29 + IRQ_GIC_START)
#define IRQ_PMU_CPU0				(30 + IRQ_GIC_START)
#define IRQ_PMU_CPU1				(31 + IRQ_GIC_START)

#define IRQ_APB_GPIOINST0			(32 + IRQ_GIC_START)
#define IRQ_APB_GPIOINST1			(33 + IRQ_GIC_START)
#define IRQ_APB_GPIOINST2			(34 + IRQ_GIC_START)
#define IRQ_APB_GPIOINST3			(35 + IRQ_GIC_START)
#define IRQ_APB_SSIINST1			(36 + IRQ_GIC_START)
#define IRQ_APB_WDTINST0			(37 + IRQ_GIC_START)
#define IRQ_APB_WDTINST1			(38 + IRQ_GIC_START)
#define IRQ_APB_WDTINST2			(39 + IRQ_GIC_START)
#define IRQ_APB_TIMERINST1_0			(40 + IRQ_GIC_START)
#define IRQ_APB_TIMERINST1_1			(41 + IRQ_GIC_START)
#define IRQ_APB_TIMERINST1_2			(42 + IRQ_GIC_START)
#define IRQ_APB_TIMERINST1_3			(43 + IRQ_GIC_START)
#define IRQ_APB_TIMERINST1_4			(44 + IRQ_GIC_START)
#define IRQ_APB_TIMERINST1_5			(45 + IRQ_GIC_START)
#define IRQ_APB_TIMERINST1_6			(46 + IRQ_GIC_START)
#define IRQ_APB_TIMERINST1_7			(47 + IRQ_GIC_START)
#define IRQ_APB_I2CINST0			(48 + IRQ_GIC_START)
#define IRQ_APB_I2CINST1_IC_GEN_CALL_INTR	(49 + IRQ_GIC_START)
#define IRQ_APB_I2CINST1_IC_RX_UNDER_INTR	(50 + IRQ_GIC_START)
#define IRQ_APB_I2CINST1_IC_RX_OVER_INTR	(51 + IRQ_GIC_START)
#define IRQ_APB_I2CINST1_IC_RX_FULL_INTR	(52 + IRQ_GIC_START)
#define IRQ_APB_I2CINST1_IC_TX_OVER_INTR	(53 + IRQ_GIC_START)
#define IRQ_APB_I2CINST1_IC_TX_EMPTY_INTR	(54 + IRQ_GIC_START)
#define IRQ_APB_I2CINST1_IC_RD_REQ_INTR		(55 + IRQ_GIC_START)
#define IRQ_APB_I2CINST1_IC_TX_ABRT_INTR	(56 + IRQ_GIC_START)
#define IRQ_APB_I2CINST1_IC_RX_DONE_INTR	(57 + IRQ_GIC_START)
#define IRQ_APB_I2CINST1_IC_ACTIVITY_INTR	(58 + IRQ_GIC_START)
#define IRQ_APB_I2CINST1_IC_STOP_DET_INTR	(59 + IRQ_GIC_START)
#define IRQ_APB_I2CINST1_IC_START_DET_INTR	(60 + IRQ_GIC_START)

#define IRQ_SM_WATCHDOG0			(64 + IRQ_GIC_START)
#define IRQ_SM_WATCHDOG1			(65 + IRQ_GIC_START)
#define IRQ_SM_WATCHDOG2			(66 + IRQ_GIC_START)
#define IRQ_SM_TIMERS				(67 + IRQ_GIC_START)
#define IRQ_SM_GPIO1				(68 + IRQ_GIC_START)
#define IRQ_SM_SPI				(69 + IRQ_GIC_START)
#define IRQ_SM_I2C0				(70 + IRQ_GIC_START)
#define IRQ_SM_I2C1				(71 + IRQ_GIC_START)
#define IRQ_SM_UART0				(72 + IRQ_GIC_START)
#define IRQ_SM_UART1				(73 + IRQ_GIC_START)
#define IRQ_SM_UART2				(74 + IRQ_GIC_START)
#define IRQ_SM_GPIO0				(75 + IRQ_GIC_START)
#define IRQ_SM_ADC				(76 + IRQ_GIC_START)
#define IRQ_SM_SOC2SM				(77 + IRQ_GIC_START)
#define IRQ_SM_TSEN				(78 + IRQ_GIC_START)
#define IRQ_SM_WOL				(79 + IRQ_GIC_START)
#define IRQ_SM_CEC				(80 + IRQ_GIC_START)
#define IRQ_SM_FIFO				(81 + IRQ_GIC_START)
#define IRQ_SM_ETH				(82 + IRQ_GIC_START)
#define IRQ_SM_HPD				(83 + IRQ_GIC_START)
#define IRQ_SM_IHPD				(84 + IRQ_GIC_START)
#define IRQ_SM_HDMIRXPWR			(85 + IRQ_GIC_START)
#define IRQ_SM_IHDMIRXPWR			(86 + IRQ_GIC_START)

#define NR_IRQS					IRQ_SM_IHDMIRXPWR

/* For compatible with Galois */
#define IRQ_APB_TWSIINST0	IRQ_APB_I2CINST0
#define IRQ_APB_TWSIINST1	IRQ_APB_I2CINST1_IC_GEN_CALL_INTR
#define IRQ_APB_TWSIINST2	IRQ_SM_I2C0
#define IRQ_APB_TWSIINST3	IRQ_SM_I2C1

#endif /* __ASM_MACH_IRQS_H */
