/*
 * Key mapping table for VIA+ Remote Controller
 */
static struct ir_keymap keymap_tab[] = {
	MAKE_IR_KEYMAP(MV_IR_KEY_NULL,          0, KEY_RESERVED), /* no key */
	MAKE_IR_KEYMAP(MV_IR_KEY_POWER,         0, KEY_POWER),
	MAKE_IR_KEYMAP(MV_IR_KEY_OPENCLOSE,     0, KEY_OPEN),

	/* digital keys */
	MAKE_IR_KEYMAP(MV_IR_KEY_DIGIT_1,       0, KEY_1),
	MAKE_IR_KEYMAP(MV_IR_KEY_DIGIT_2,       0, KEY_2),
	MAKE_IR_KEYMAP(MV_IR_KEY_DIGIT_3,       0, KEY_3),
	MAKE_IR_KEYMAP(MV_IR_KEY_DIGIT_4,       0, KEY_4),
	MAKE_IR_KEYMAP(MV_IR_KEY_DIGIT_5,       0, KEY_5),
	MAKE_IR_KEYMAP(MV_IR_KEY_DIGIT_6,       0, KEY_6),
	MAKE_IR_KEYMAP(MV_IR_KEY_DIGIT_7,       0, KEY_7),
	MAKE_IR_KEYMAP(MV_IR_KEY_DIGIT_8,       0, KEY_8),
	MAKE_IR_KEYMAP(MV_IR_KEY_DIGIT_9,       0, KEY_9),
	MAKE_IR_KEYMAP(MV_IR_KEY_DIGIT_0,       0, KEY_0),

	/* for BD */
	MAKE_IR_KEYMAP(MV_IR_KEY_INFO,          0, KEY_PROGRAM_INFO),
	MAKE_IR_KEYMAP(MV_IR_KEY_SETUPMENU,     0, KEY_MENU),
	MAKE_IR_KEYMAP(MV_IR_KEY_CANCEL,        0, KEY_CANCEL),	/* no key */

	MAKE_IR_KEYMAP(MV_IR_KEY_DISCMENU,      0, KEY_CONTEXT_MENU),
	MAKE_IR_KEYMAP(MV_IR_KEY_TITLEMENU,     0, KEY_TITLE),
	MAKE_IR_KEYMAP(MV_IR_KEY_SUBTITLE,      0, KEY_SUBTITLE),
	MAKE_IR_KEYMAP(MV_IR_KEY_ANGLE,         0, KEY_ANGLE),
	MAKE_IR_KEYMAP(MV_IR_KEY_AUDIO,         0, KEY_AUDIO),
	MAKE_IR_KEYMAP(MV_IR_KEY_SEARCH,        0, KEY_SEARCH),
	MAKE_IR_KEYMAP(MV_IR_KEY_ZOOM,          0, KEY_ZOOM),
	MAKE_IR_KEYMAP(MV_IR_KEY_DISPLAY,       0, KEY_SCREEN),

	MAKE_IR_KEYMAP(MV_IR_KEY_REPEAT,        0, KEY_MEDIA_REPEAT),
	MAKE_IR_KEYMAP(MV_IR_KEY_REPEAT_AB,     0, KEY_AB),
	MAKE_IR_KEYMAP(MV_IR_KEY_MARKER,        0, KEY_MARKER),
	MAKE_IR_KEYMAP(MV_IR_KEY_EXIT,          0, KEY_EXIT),
	MAKE_IR_KEYMAP(MV_IR_KEY_A,             0, KEY_RED),
	MAKE_IR_KEYMAP(MV_IR_KEY_B,             0, KEY_GREEN),
	MAKE_IR_KEYMAP(MV_IR_KEY_C,             0, KEY_YELLOW),
	MAKE_IR_KEYMAP(MV_IR_KEY_D,             0, KEY_BLUE),

	/* IR misc around ENTER */
	MAKE_IR_KEYMAP(MV_IR_KEY_CLEAR,         0, KEY_CLEAR),
	MAKE_IR_KEYMAP(MV_IR_KEY_VIDEO_FORMAT,  0, KEY_VIDEO),
	MAKE_IR_KEYMAP(MV_IR_KEY_STEP,          0, KEY_STEP),
	MAKE_IR_KEYMAP(MV_IR_KEY_RETURN,        0, KEY_ESC),

	/* up down left right enter */
	MAKE_IR_KEYMAP(MV_IR_KEY_UP,            0, KEY_UP),
	MAKE_IR_KEYMAP(MV_IR_KEY_DOWN,          0, KEY_DOWN),
	MAKE_IR_KEYMAP(MV_IR_KEY_LEFT,          0, KEY_LEFT),
	MAKE_IR_KEYMAP(MV_IR_KEY_RIGHT,         0, KEY_RIGHT),
	MAKE_IR_KEYMAP(MV_IR_KEY_ENTER,         0, KEY_ENTER),

	/* for BD */
	MAKE_IR_KEYMAP(MV_IR_KEY_SLOW,          0, KEY_SLOW),
	MAKE_IR_KEYMAP(MV_IR_KEY_PAUSE,         0, KEY_PAUSE),
	MAKE_IR_KEYMAP(MV_IR_KEY_PLAY,          0, KEY_PLAY),
	MAKE_IR_KEYMAP(MV_IR_KEY_STOP,          0, KEY_STOP),
	MAKE_IR_KEYMAP(MV_IR_KEY_PLAY_PAUSE,    0, KEY_PLAYPAUSE), /* no key */

	MAKE_IR_KEYMAP(MV_IR_KEY_SKIP_BACKWARD, 0, KEY_PREVIOUS),
	MAKE_IR_KEYMAP(MV_IR_KEY_SKIP_FORWARD,  0, KEY_NEXT),
	MAKE_IR_KEYMAP(MV_IR_KEY_SLOW_BACKWARD, 0, KEY_RESERVED), /* no key */
	MAKE_IR_KEYMAP(MV_IR_KEY_SLOW_FORWARD,  0, KEY_RESERVED), /* no key */
	MAKE_IR_KEYMAP(MV_IR_KEY_FAST_BACKWARD, 0, KEY_REWIND),
	MAKE_IR_KEYMAP(MV_IR_KEY_FAST_FORWARD,  0, KEY_FORWARD),

	/* bottom keys */
	MAKE_IR_KEYMAP(MV_IR_KEY_F1,            0, KEY_F1), /* TV */
	MAKE_IR_KEYMAP(MV_IR_KEY_F2,            0, KEY_F2), /* HOME */
	MAKE_IR_KEYMAP(MV_IR_KEY_F3,            0, KEY_F3), /* BACK */
	MAKE_IR_KEYMAP(MV_IR_KEY_F4,            0, KEY_F4), /* MENU */
	MAKE_IR_KEYMAP(MV_IR_KEY_F5,            0, KEY_F5), /* INFO */
	MAKE_IR_KEYMAP(MV_IR_KEY_F6,            0, KEY_F6), /* WINDOW */
	MAKE_IR_KEYMAP(MV_IR_KEY_F7,            0, KEY_F7), /* GUIDE */
	MAKE_IR_KEYMAP(MV_IR_KEY_F8,            0, KEY_F8), /* DVR */

	/* for future */
	MAKE_IR_KEYMAP(MV_IR_KEY_VOL_PLUS,      0, KEY_VOLUMEUP),   /* no key */
	MAKE_IR_KEYMAP(MV_IR_KEY_VOL_MINUS,     0, KEY_VOLUMEDOWN), /* no key */
	MAKE_IR_KEYMAP(MV_IR_KEY_VOL_MUTE,      0, KEY_MUTE),       /* no key */
	MAKE_IR_KEYMAP(MV_IR_KEY_CHANNEL_PLUS,  0, KEY_CHANNELUP),  /* no key */
	MAKE_IR_KEYMAP(MV_IR_KEY_CHANNEL_MINUS, 0, KEY_CHANNELDOWN),/* no key */

	/* obsoleted keys */
	MAKE_IR_KEYMAP(MV_IR_KEY_MENU,          0, KEY_MENU),
	MAKE_IR_KEYMAP(MV_IR_KEY_INPUTSEL,      0, KEY_RESERVED),
	MAKE_IR_KEYMAP(MV_IR_KEY_ANYNET,        0, KEY_RESERVED),
	MAKE_IR_KEYMAP(MV_IR_KEY_TELEVISION,    0, KEY_TV),
	MAKE_IR_KEYMAP(MV_IR_KEY_CHANNEL_LIST,  0, KEY_RESERVED),
	MAKE_IR_KEYMAP(MV_IR_KEY_TVPOWER,       0, KEY_RESERVED),

	/* for DTV */
	MAKE_IR_KEYMAP(MV_IR_KEY_TV_INPUT,      0, KEY_TV_INPUT),
	MAKE_IR_KEYMAP(MV_IR_KEY_LIST,          0, KEY_LIST),
	MAKE_IR_KEYMAP(MV_IR_KEY_REC,           0, KEY_RECORD),
	MAKE_IR_KEYMAP(MV_IR_KEY_LAST,          0, KEY_LAST),
	MAKE_IR_KEYMAP(MV_IR_KEY_GUIDE,	        0, KEY_PROGRAM),
	MAKE_IR_KEYMAP(MV_IR_KEY_BACK,          0, KEY_BACK),

	/* Specific/Custom keys */
	MAKE_IR_KEYMAP(MV_IR_KEY_AMAZON,        0, KEY_FN_F1),
	MAKE_IR_KEYMAP(MV_IR_KEY_NETFLIX,       0, KEY_FN_F2),
	MAKE_IR_KEYMAP(MV_IR_KEY_VUDU,          0, KEY_FN_F3),
	MAKE_IR_KEYMAP(MV_IR_KEY_PIP,           0, KEY_F6),    /* WINDOW */
	MAKE_IR_KEYMAP(MV_IR_KEY_LIVE_TV,       0, KEY_TV),
	MAKE_IR_KEYMAP(MV_IR_KEY_VIA,           0, KEY_HOME),
	MAKE_IR_KEYMAP(MV_IR_KEY_QUICK,         0, KEY_FN_F4),
	MAKE_IR_KEYMAP(MV_IR_KEY_DASH,          0, KEY_FN_F5),
	MAKE_IR_KEYMAP(MV_IR_KEY_M_GO,       	0, KEY_FN_F6),

	/* Game Pad */
	MAKE_IR_KEYMAP(MV_IR_BTN_UP,            0, KEY_UP),
	MAKE_IR_KEYMAP(MV_IR_BTN_DOWN,          0, KEY_DOWN),
	MAKE_IR_KEYMAP(MV_IR_BTN_LEFT,          0, KEY_LEFT),
	MAKE_IR_KEYMAP(MV_IR_BTN_RIGHT,         0, KEY_RIGHT),
	MAKE_IR_KEYMAP(MV_IR_BTN_X,             0, BTN_X),
	MAKE_IR_KEYMAP(MV_IR_BTN_Y,             0, BTN_Y),
	MAKE_IR_KEYMAP(MV_IR_BTN_A,             0, BTN_A),
	MAKE_IR_KEYMAP(MV_IR_BTN_B,             0, BTN_B),

	/*  qwerty keyboard */
	MAKE_IR_KEYMAP(MV_IR_KB_TAB,            0, KEY_TAB),
	MAKE_IR_KEYMAP(MV_IR_KB_ESC,            0, KEY_ESC),
	MAKE_IR_KEYMAP(MV_IR_KB_SEMICOLON,      0, KEY_SEMICOLON),
	MAKE_IR_KEYMAP(MV_IR_KB_SPACE,          0, KEY_SPACE),
	MAKE_IR_KEYMAP(MV_IR_KB_COMMA,          0, KEY_COMMA),
	MAKE_IR_KEYMAP(MV_IR_KB_DOT,            0, KEY_DOT),
	MAKE_IR_KEYMAP(MV_IR_KB_BACKSLASH,      0, KEY_BACKSLASH),
	MAKE_IR_KEYMAP(MV_IR_KB_SLASH,          0, KEY_SLASH),
	MAKE_IR_KEYMAP(MV_IR_KB_APOSTROPHE,     0, KEY_APOSTROPHE),
	MAKE_IR_KEYMAP(MV_IR_KB_EQUAL,          0, KEY_EQUAL),
	MAKE_IR_KEYMAP(MV_IR_KB_BACKSPACE,      0, KEY_BACKSPACE),
	MAKE_IR_KEYMAP(MV_IR_KB_ENTER,          0, KEY_ENTER),
	MAKE_IR_KEYMAP(MV_IR_KB_DELETE,         0, KEY_DELETE),
	MAKE_IR_KEYMAP(MV_IR_KB_GRAVE,          0, KEY_GRAVE),
	MAKE_IR_KEYMAP(MV_IR_KB_MINUS,          0, KEY_MINUS),
	MAKE_IR_KEYMAP(MV_IR_KB_LEFTBRACE,      0, KEY_LEFTBRACE),
	MAKE_IR_KEYMAP(MV_IR_KB_RIGHTBRACE,     0, KEY_RIGHTBRACE),

	MAKE_IR_KEYMAP(MV_IR_KB_A,              0, KEY_A),
	MAKE_IR_KEYMAP(MV_IR_KB_B,              0, KEY_B),
	MAKE_IR_KEYMAP(MV_IR_KB_C,              0, KEY_C),
	MAKE_IR_KEYMAP(MV_IR_KB_D,              0, KEY_D),
	MAKE_IR_KEYMAP(MV_IR_KB_E,              0, KEY_E),
	MAKE_IR_KEYMAP(MV_IR_KB_F,              0, KEY_F),
	MAKE_IR_KEYMAP(MV_IR_KB_G,              0, KEY_G),
	MAKE_IR_KEYMAP(MV_IR_KB_H,              0, KEY_H),
	MAKE_IR_KEYMAP(MV_IR_KB_I,              0, KEY_I),
	MAKE_IR_KEYMAP(MV_IR_KB_J,              0, KEY_J),
	MAKE_IR_KEYMAP(MV_IR_KB_K,              0, KEY_K),
	MAKE_IR_KEYMAP(MV_IR_KB_L,              0, KEY_L),
	MAKE_IR_KEYMAP(MV_IR_KB_M,              0, KEY_M),
	MAKE_IR_KEYMAP(MV_IR_KB_N,              0, KEY_N),
	MAKE_IR_KEYMAP(MV_IR_KB_O,              0, KEY_O),
	MAKE_IR_KEYMAP(MV_IR_KB_P,              0, KEY_P),
	MAKE_IR_KEYMAP(MV_IR_KB_Q,              0, KEY_Q),
	MAKE_IR_KEYMAP(MV_IR_KB_R,              0, KEY_R),
	MAKE_IR_KEYMAP(MV_IR_KB_S,              0, KEY_S),
	MAKE_IR_KEYMAP(MV_IR_KB_T,              0, KEY_T),
	MAKE_IR_KEYMAP(MV_IR_KB_U,              0, KEY_U),
	MAKE_IR_KEYMAP(MV_IR_KB_V,              0, KEY_V),
	MAKE_IR_KEYMAP(MV_IR_KB_W,              0, KEY_W),
	MAKE_IR_KEYMAP(MV_IR_KB_X,              0, KEY_X),
	MAKE_IR_KEYMAP(MV_IR_KB_Y,              0, KEY_Y),
	MAKE_IR_KEYMAP(MV_IR_KB_Z,              0, KEY_Z),

	MAKE_IR_KEYMAP(MV_IR_KB_KP1,            0, KEY_KP1),
	MAKE_IR_KEYMAP(MV_IR_KB_KP2,            0, KEY_KP2),
	MAKE_IR_KEYMAP(MV_IR_KB_KP3,            0, KEY_KP3),
	MAKE_IR_KEYMAP(MV_IR_KB_KP4,            0, KEY_KP4),
	MAKE_IR_KEYMAP(MV_IR_KB_KP5,            0, KEY_KP5),
	MAKE_IR_KEYMAP(MV_IR_KB_KP6,            0, KEY_KP6),
	MAKE_IR_KEYMAP(MV_IR_KB_KP7,            0, KEY_KP7),
	MAKE_IR_KEYMAP(MV_IR_KB_KP8,            0, KEY_KP8),
	MAKE_IR_KEYMAP(MV_IR_KB_KP9,            0, KEY_KP9),
	MAKE_IR_KEYMAP(MV_IR_KB_KP0,            0, KEY_KP0),

	/* Special factory reset key */
	MAKE_IR_KEYMAP(MV_HARD_KEY_FACTORY_RESET, 0, KEY_DEMO_MODE),

#define KEY_SHIFT KEY_LEFTSHIFT
	/* Compose keys */
	MAKE_IR_KEYMAP(MV_IR_KB_UPPER_A,        KEY_SHIFT, KEY_A),
	MAKE_IR_KEYMAP(MV_IR_KB_UPPER_B,        KEY_SHIFT, KEY_B),
	MAKE_IR_KEYMAP(MV_IR_KB_UPPER_C,        KEY_SHIFT, KEY_C),
	MAKE_IR_KEYMAP(MV_IR_KB_UPPER_D,        KEY_SHIFT, KEY_D),
	MAKE_IR_KEYMAP(MV_IR_KB_UPPER_E,        KEY_SHIFT, KEY_E),
	MAKE_IR_KEYMAP(MV_IR_KB_UPPER_F,        KEY_SHIFT, KEY_F),
	MAKE_IR_KEYMAP(MV_IR_KB_UPPER_G,        KEY_SHIFT, KEY_G),
	MAKE_IR_KEYMAP(MV_IR_KB_UPPER_H,        KEY_SHIFT, KEY_H),
	MAKE_IR_KEYMAP(MV_IR_KB_UPPER_I,        KEY_SHIFT, KEY_I),
	MAKE_IR_KEYMAP(MV_IR_KB_UPPER_J,        KEY_SHIFT, KEY_J),
	MAKE_IR_KEYMAP(MV_IR_KB_UPPER_K,        KEY_SHIFT, KEY_K),
	MAKE_IR_KEYMAP(MV_IR_KB_UPPER_L,        KEY_SHIFT, KEY_L),
	MAKE_IR_KEYMAP(MV_IR_KB_UPPER_M,        KEY_SHIFT, KEY_M),
	MAKE_IR_KEYMAP(MV_IR_KB_UPPER_N,        KEY_SHIFT, KEY_N),
	MAKE_IR_KEYMAP(MV_IR_KB_UPPER_O,        KEY_SHIFT, KEY_O),
	MAKE_IR_KEYMAP(MV_IR_KB_UPPER_P,        KEY_SHIFT, KEY_P),
	MAKE_IR_KEYMAP(MV_IR_KB_UPPER_Q,        KEY_SHIFT, KEY_Q),
	MAKE_IR_KEYMAP(MV_IR_KB_UPPER_R,        KEY_SHIFT, KEY_R),
	MAKE_IR_KEYMAP(MV_IR_KB_UPPER_S,        KEY_SHIFT, KEY_S),
	MAKE_IR_KEYMAP(MV_IR_KB_UPPER_T,        KEY_SHIFT, KEY_T),
	MAKE_IR_KEYMAP(MV_IR_KB_UPPER_U,        KEY_SHIFT, KEY_U),
	MAKE_IR_KEYMAP(MV_IR_KB_UPPER_V,        KEY_SHIFT, KEY_V),
	MAKE_IR_KEYMAP(MV_IR_KB_UPPER_W,        KEY_SHIFT, KEY_W),
	MAKE_IR_KEYMAP(MV_IR_KB_UPPER_X,        KEY_SHIFT, KEY_X),
	MAKE_IR_KEYMAP(MV_IR_KB_UPPER_Y,        KEY_SHIFT, KEY_Y),
	MAKE_IR_KEYMAP(MV_IR_KB_UPPER_Z,        KEY_SHIFT, KEY_Z),
	MAKE_IR_KEYMAP(MV_IR_KB_TILDE,          KEY_SHIFT, KEY_GRAVE),
	MAKE_IR_KEYMAP(MV_IR_KB_FACTORIAL,      KEY_SHIFT, KEY_1),
	MAKE_IR_KEYMAP(MV_IR_KB_AT,             KEY_SHIFT, KEY_2),
	MAKE_IR_KEYMAP(MV_IR_KB_SHARP,          KEY_SHIFT, KEY_3),
	MAKE_IR_KEYMAP(MV_IR_KB_DOLLAR,         KEY_SHIFT, KEY_4),
	MAKE_IR_KEYMAP(MV_IR_KB_PERCENTAGE,     KEY_SHIFT, KEY_5),
	MAKE_IR_KEYMAP(MV_IR_KB_CARET,          KEY_SHIFT, KEY_6),
	MAKE_IR_KEYMAP(MV_IR_KB_AND,            KEY_SHIFT, KEY_7),
	MAKE_IR_KEYMAP(MV_IR_KB_ASTERISK,       KEY_SHIFT, KEY_8),
	MAKE_IR_KEYMAP(MV_IR_KB_LEFTRBRACKET,   KEY_SHIFT, KEY_9),
	MAKE_IR_KEYMAP(MV_IR_KB_RIGHTRBRACKET,  KEY_SHIFT, KEY_0),
	MAKE_IR_KEYMAP(MV_IR_KB_UNDERSCORE,     KEY_SHIFT, KEY_MINUS),
	MAKE_IR_KEYMAP(MV_IR_KB_PLUS,           KEY_SHIFT, KEY_EQUAL),
	MAKE_IR_KEYMAP(MV_IR_KB_LEFTCBRACKET,   KEY_SHIFT, KEY_LEFTBRACE),
	MAKE_IR_KEYMAP(MV_IR_KB_RIGHTCBRACKET,  KEY_SHIFT, KEY_RIGHTBRACE),
	MAKE_IR_KEYMAP(MV_IR_KB_OR,             KEY_SHIFT, KEY_BACKSLASH),
	MAKE_IR_KEYMAP(MV_IR_KB_COLON,          KEY_SHIFT, KEY_SEMICOLON),
	MAKE_IR_KEYMAP(MV_IR_KB_QUOTATION,      KEY_SHIFT, KEY_APOSTROPHE),
	MAKE_IR_KEYMAP(MV_IR_KB_LEFTABRACKET,   KEY_SHIFT, KEY_COMMA),
	MAKE_IR_KEYMAP(MV_IR_KB_RIGHTABRACKET,  KEY_SHIFT, KEY_DOT),
	MAKE_IR_KEYMAP(MV_IR_KB_QUESTION,       KEY_SHIFT, KEY_SLASH),
};
